### PR TITLE
Implemented: "I think that rangeOfOnes should generate a run containe…

### PR DESCRIPTION
**Pull request by lemire**
…r, see https://github.com/glycerine/roaring/blob/master/roaringarray.go#L53-L59"

See https://github.com/RoaringBitmap/roaring/pull/70#issuecomment-263949320

### CODE REVIEW

**Comment by glycerine** [comment]
Great!

One small but important suggestion:

summary: Add the function as newRunContainer32Range to rle.go, then run "make rle"

Explanation: since I was regularly generating rle16.go from rle.go automatically (see the Makefile target rle, as in "make rle") I suggest that this convention be maintained: make the change to the rle.go file, then run "make rle" to generate rle16.go. That way the 16 and 32 bit versions are always in sync. If a function/method applies to both 16 and 32-bit, then it goes in rlecommon.go.

Does that make sense?

**Comment by lemire** [comment]
@glycerine  

Done.

I added a ``backrle`` target that enables me to modify ``rle16.go`` and get ``rle.go`` as a side-effect.

**Comment by glycerine** [comment]
LGTM

**Comment by lemire** [comment]
Great. Next step is to implement a ``RunOptimize`` function. Should not be too hard, but I think it will require a couple of new functions.

**Comment by glycerine** [comment]
sounds good. I wish I had more time to work on this, but I'm happy to do quick pr reviews.

**Pull request merged**
